services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: car_repair_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  car_repair_shop:
    build: ./
    container_name: car_repair_shop
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/car_repair_shop
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  db_data:

