spring:
  application:
    name: car-repair-shop

  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update